### ISSUE TITLE
Roadmap to version 1.0

### ISSUE THREAD

**Issue by VitorLuizC** [VitorLuizC/normalize-text#3]
- [x] Remove `uncouple` dependency.
- [x] Move to "not soo functional" way.
  - [x] Remove `compose` function.
- [x] Use TypeScript, even on tests.
